### ISSUE TITLE
Having issue to read the SPIFF file.

### ISSUE THREAD

**Issue by OttoKlaasen** [khoih-prog/ESP_WiFiManager#14]
Dear Sir,
following code does not seem to work:

    // we could open the file
    size_t size = f.size();
    // Allocate a buffer to store contents of the file.
    std::unique_ptr<char[]> buf(new char[size]);
    // Read and store file contents in buf
    f.readBytes(buf.get(), size);

I get rubish in buf, i had to rewrite like this to be able to read by SPIFF file:

 File f = SPIFFS.open(CONFIG_FILE, "r");
 String buffer;   /// Create a string buffer to get the file contents
	// 
  Serial.println("Get file");
	if (!f) Serial.println("FAIL TO LOAD FILE");
	while (f.available()){
		  buffer = f.readString().c_str();
      }
  Serial.print("file buffer: ");Serial.println(String(buffer)); // Print buffer which contains file contents

  char * doc = new char [buffer.length()+1];  // Define a pointer to a char buffer called doc
  std::strcpy (doc, buffer.c_str());          // Copy string buffer to char buffer caled doc

  Serial.print("doc: ");Serial.println(String(doc));   // Print doc as string
    // Do the joson stuff
    StaticJsonDocument<1024> json;
    Serial.println("deserialize !");

of course add this in a header file:
// strings and c-strings
#include <iostream>
#include <cstring>
#include <string>

Cheers and greetings from the netherland.

**Comment by khoih-prog** [comment]
Hello,
Thanks for using the library and finding out the bug/mistake.
The issue is that the buffer is not allocated large enough, lacking one NULL terminating byte.

Please change the corresponding code of these affected examples
1. [ConfigOnSwitchFS](examples/ConfigOnSwitchFS)
2. [ConfigPortalParamsOnSwitch](examples/ConfigPortalParamsOnSwitch)
to
```cpp
// we could open the file
    size_t size = f.size();
    // Allocate a buffer to store contents of the file.
    std::unique_ptr<char[]> buf(new char[size + 1]);
```
from
```cpp
// we could open the file
    size_t size = f.size();
    // Allocate a buffer to store contents of the file.
    std::unique_ptr<char[]> buf(new char[size]);
```
The [AutoConnectWithFSParameters](examples/AutoConnectWithFSParameters) is still OK with correct code
```cpp
        size_t configFileSize = configFile.size();
        Serial.println(configFileSize);

        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[configFileSize + 1]);
```
Your solution is working OK and you can keep using it.
Those examples will be uploaded to the Master, and included in the next Release.

Regards,
