### ISSUE TITLE
Image in Server

### ISSUE THREAD

**Issue by rodrigopachecoribas** [khoih-prog/ESP_WiFiManager#43]
Good morning,

Very good this wifiManager. Is possible out one image.jpg in wifimanager? How can i send a image to WebServer?

Thank You,
Rodrigo Ribas

**Comment by khoih-prog** [comment]
Hi Rodrigo,

This is a [**ESP_WiFiManager Library**](https://github.com/khoih-prog/ESP_WiFiManager) is just a WiFiManager providing you a Configuration Portal so that you can modify your parameters on-the-fly, without hard-coding in the sketch.

To send image to WebServer, you need to use other libraries or even features already provided in ESP32/ESP8266.

I suggest you to do some search/research on the Internet to know how to do that.

Good Luck,
