### ISSUE TITLE
Problem when de-energizing the ESP8266

### ISSUE THREAD

**Issue by latorudo** [khoih-prog/ESP_WiFiManager#44]
Hello Mr KHOIH. First I would like to congratulate you on your brilliant work.
It worked perfectly on my ESP32 Nodemcu. Now I am migrating to ESP8266, but using the same example "ConfigOnswitch", it does not save the SSID and password parameters when de-energizing ESP8266. So he returns to the config mode. Is there a parameter that I should change to work well as in ESP32?

Greetings from Brazil

**Comment by khoih-prog** [comment]
Hi @latorudo 

It's good to know that the library is somehow helpful and working on your ESP32.

For your new ESP8266, without more information, it's difficult to guess what's happening there. You have to post at least the terminal debug output and/or screen shot, and also the sketch you're using (if modified).
You can try other examples to see if the issue is the bad board or not.

I suggest that you also check these 

1. The [**ConfigOnSwitch**](https://github.com/khoih-prog/ESP_WiFiManager/tree/master/examples/ConfigOnSwitch) example will check, for **ESP8266**, the **D3** and **D7** pins, and enters the Config Portal if any of those pins is connected to GND in startup. **Change to other pins if conflict with your current usage.**

```
/* Trigger for inititating config mode is Pin D3 and also flash button on NodeMCU
   Flash button is convenient to use but if it is pressed it will stuff up the serial port device driver
   until the computer is rebooted on windows machines.
*/
const int TRIGGER_PIN = PIN_D3; // D3 on NodeMCU and WeMos.
/*
   Alternative trigger pin. Needs to be connected to a button to use this pin. It must be a momentary connection
   not connected permanently to ground. Either trigger pin will work.
*/
const int TRIGGER_PIN2 = PIN_D7; // D7 on NodeMCU and WeMos.
```

2. Be sure **`FORMAT_FILESYSTEM`** is set to `false`. This can be set to `true` only once for new board to format the **SPIFFS** or **LittleFS** file system, the to `false` thereafter.

```
// From v1.1.0
// You only need to format the filesystem once
//#define FORMAT_FILESYSTEM       true
#define FORMAT_FILESYSTEM         false
```

Good luck,
