### ISSUE TITLE
Webserver using SSL

### ISSUE THREAD

**Issue by SquallHalle** [khoih-prog/ESP_WiFiManager#54]
Hey there!
Nice Project and stunning fast captive portal.
Do you see any chance to add ssl to the webserver 
(like this one https://techtutorialsx.com/2019/04/07/esp32-https-web-server/) 
Greetings

**Comment by khoih-prog** [comment]
HI @SquallHalle 

Thanks for using the library and your nice words.
I don't have any plan and even against to update the library to use **SSL WebServer** because 

1. This Config Portal (CP) is **short lived** and doesn't need drastic security measures.
2. Using SSL will dramatically and unnecessary **increase code size and executing time**
3. SSL using self-signed Certificate will make CP connection more difficult because some browsers will give **warnings and complex steps** before let users to access.
4. SSL, using official SSL Certificates will be very **complicated, expensive**, especially for normal users.

If you need that SSL feature for some reasons, you just fork, modify and use.

Regards,
