### ISSUE TITLE
Doesn't save network credentials

### ISSUE THREAD

**Issue by Philipp66904** [khoih-prog/ESP_WiFiManager#64]
### Describe the bug

I used following demo-programm after noticing it in my own code: "Async_AutoConnect_ESP8266_minimal.ino"

I use an ESP8266 with core v3.0.0 

### Steps to Reproduce

I upload the code to my device and it starts the config portal with AP as exepected. I enter the correct network credentials and the ESP connects to my Network without a problem.
But after restarting the ESP, it seems that it didn't save my credentials at all and I have to dial them in again. This happens over and over again without changing.

### Expected behavior

After the first time saving the credentials it should automatically connect to the network.

### Actual behavior

It asks me about my network again and says that there are no networks saved.

### Information

Please ensure to specify the following:

* Arduino IDE version 1.8.15
* `ESP8266` core v3.0.0

**Comment by khoih-prog** [comment]
Thanks for your interest in the other library [**ESPAsync_WiFiManager**](https://github.com/khoih-prog/ESPAsync_WiFiManager)

It's possible you didn't follow all the steps correctly (settings, savings, etc.) or hardware issue (SPIFFS/LittleFS/EEPROM, etc).

Try other examples, such as [**Async_ConfigOnDoubleReset**](https://github.com/khoih-prog/ESPAsync_WiFiManager/tree/master/examples/Async_ConfigOnDoubleReset) to see if the problem persists.

I'd appreciate it if you can repost in the correct library with full terminal debug output so that anyone can know what's wrong.

I'm closing this issue anyway.
