### ISSUE TITLE
Ratio or ceckbox

### ISSUE THREAD

**Issue by Barone1968** [khoih-prog/ESP_WiFiManager#72]
I can't understand The right   law for insert in the parameters a ratio / or CeckBox or switch that when 
 I saved and that when reopening it will bring me back the previously saved value, even if I save the parameter when opening it gives me the original value, can you help me thanks

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

You have to know that the library, is designed for general use cases only, and your requirements is way far of normal use cases.

I suggest that you do some research yourself, and/or post issuse on certain forums, such as Arduino, etc. to ask for help.

Be sure to include as more details as possible, because I'm afraid no one can help you with your current way of asking question.

I'm closing the issue now as this has nothing to do with the library or its bug.

Good Luck,
