### ISSUE TITLE
WiFI doesn't show up on ConfigOnDoubleReset_Multi code

### ISSUE THREAD

**Issue by giuseppemauro99** [khoih-prog/ESP_WiFiManager#88]
### Describe the bug

Hello, when running the code to create a simple AP with WiFi using this library, i see all the right message in the serial monitor but **i didn't see the wifi network** (i tried with several devices and in the serial monitor not message show up).
The problem is with the board **ESP32-WROOM-32U** and i compiled with Arduino IDE selecting different board (i tried with esp32 dev module, fire beetle esp32 nad DOIT KIT ESP32).

I tried the code example in your repo called **ConfigOnDoubleReset_Multi**

### Steps to Reproduce

Compile ConfigOnDoubleReset_Multi on ESP32-WROOM-32U

### Expected behavior

Create an AP

### Actual behavior

Didn't create an AP and not show up error message

### Debug and AT-command log (if applicable)

No error message

### Screenshots

No strange message on serial monitor, all seems ok

### Information

Please ensure to specify the following:

* Arduino IDE 2.0.0
* ESP32-WROOM-32U
* Windows 10

**Comment by khoih-prog** [comment]
HI @giuseppemauro99 

Sorry you must have done something **wrong** or your network is so **crowded** or your board is **bad**. If you don't see the AP, try to reset to auto-select another WiFi channel, to avoid being possibly **duplicated** and **masked** by a stronger one. Also try the simple examples, such as 

1. [**WiFiAccessPoint**](https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi/examples/WiFiAccessPoint)
2. [**AP_SimpleWebServer**](https://github.com/khoih-prog/WiFiWebServer/tree/master/examples/AP_SimpleWebServer)

to be sure your board is OK before moving to more complex applications.

---

I'm having no issue here.

![Selection_057](https://user-images.githubusercontent.com/57012152/190929139-1d49b4c2-ef47-40dd-969c-b4ccecfef4c1.png)

```
Starting ConfigOnDoubleReset_Multi with DoubleResetDetect using LittleFS on ESP32_DEV
ESP_WiFiManager v1.11.0
ESP_DoubleResetDetector v1.3.2
[WM] RFC925 Hostname = ConfigOnDoubleReset
[WM] Set CORS Header to :  Your Access-Control-Allow-Origin
ESP Self-Stored: SSID = HueNet, Pass = 12345678
[WM] * Add SSID =  HueNet , PW =  12345678
Got ESP Self-Stored Credentials. Timeout 120s for Config Portal
[WM] LoadWiFiCfgFile 
[WM] OK
[WM] stationIP = 192.168.2.232 , gatewayIP = 192.168.2.1
[WM] netMask = 255.255.255.0
[WM] dns1IP = 192.168.2.1 , dns2IP = 8.8.8.8
Got stored Credentials. Timeout 120s for Config Portal
Current Timezone is not set. Enter Config Portal to set.
LittleFS Flag read = 0xD0D01234
doubleResetDetected
Saving config file...
Saving config file OK
Open Config Portal without Timeout: Double Reset Detected
Starting configuration portal @ 192.168.4.1:80, SSID = ESP_90ADC, PWD = MyESP_90ADC
[WM] WiFi.waitForConnectResult Done
[WM] SET AP
[WM] Configuring AP SSID = ESP_90ADC
[WM] AP PWD = MyESP_90ADC
[WM] AP Channel = 2
[WM] AP IP address = 192.168.4.1
[WM] HTTP server started
[WM] startConfigPortal : Enter loop
[WM] Request redirected to captive portal :  192.168.4.1
[WM] Request redirected to captive portal :  192.168.4.1
```

---

Be sure to post the issue only after you verify your board is working OK. Otherwise, repeat posting `bad issue` will get you blocked from accessing this library.

Good Luck,
